require("mkdnflow").setup {
  modules = {
    bib = false,
    buffers = true,
    conceal = false,
    cursor = true,
    folds = false,
    foldtext = false,
    links = true,
    lists = true,
    maps = true,
    paths = true,
    tables = true,
    yaml = false,
    cmp = true,
  },

  links = {
    style = "markdown",
    conceal = false,
    implicit_extension = nil,
    transform_implicit = false,
    create_on_follow_failure = true,
  },

  perspective = {
    priority = "root",
    fallback = "current",
    root_tell = ".markdownlint.json",
    nvim_wd_heel = false,
    update = false,
  },

  mappings = {
    MkdnEnter = { { "n", "v" }, "<CR>" },
    MkdnTab = false,
    MkdnSTab = false,
    MkdnNextLink = { { "n" }, "<Tab>" },
    MkdnPrevLink = { { "n" }, "<S-Tab>" },
    MkdnNextHeading = { { "n" }, "]]" },
    MkdnPrevHeading = { { "n" }, "[[" },
    MkdnGoBack = { { "n" }, "<BS>" },
    MkdnGoForward = { { "n" }, "<Del>" },
    MkdnCreateLink = false,
    MkdnCreateLinkFromClipboard = { { "n", "v" }, "<leader>p" },
    MkdnFollowLink = false,
    MkdnDestroyLink = { { "n" }, "<M-CR>" },
    MkdnTagSpan = { { "v" }, "<M-CR>" },
    MkdnMoveSource = { { "n" }, "<F2>" },
    MkdnYankAnchorLink = { { "n" }, "yaa" },
    MkdnYankFileAnchorLink = { { "n" }, "yfa" },
    MkdnIncreaseHeading = { { "n" }, "+" },
    MkdnDecreaseHeading = { { "n" }, "-" },
    MkdnToggleToDo = { { "n", "v" }, "<C-Space>" },
    MkdnNewListItem = false,
    MkdnNewListItemBelowInsert = { { "n" }, "o" },
    MkdnNewListItemAboveInsert = { { "n" }, "O" },
    MkdnExtendList = false,
    MkdnUpdateNumbering = { { "n" }, "<leader>nn" },
    MkdnTableNextCell = { { "i" }, "<Tab>" },
    MkdnTablePrevCell = { { "i" }, "<S-Tab>" },
    MkdnTableNextRow = false,
    MkdnTablePrevRow = false,
    MkdnTableNewRowBelow = { { "n" }, "<leader>ir" },
    MkdnTableNewRowAbove = { { "n" }, "<leader>iR" },
    MkdnTableNewColAfter = { { "n" }, "<leader>ic" },
    MkdnTableNewColBefore = { { "n" }, "<leader>iC" },
    MkdnFoldSection = false,
    MkdnUnfoldSection = false,
  },
}
